name:       roki-web
version:    1.0.0.0
category:   Web
author:     Roki
maintainer: falgon53@yahoo.co.jp
copyright:  Copyright (c) 2020 Roki
license:    BSD3
github:     roki/roki-web

extra-source-files:
    - README.md

dependencies:
    - aeson
    - base
    - binary
    - hakyll
    - hakyll-sass
    - tagsoup
    - process
    - bytestring
    - unordered-containers
    - basic-prelude
    - pandoc
    - filepath
    - time
    - text
    - lucid
    - mtl
    - containers
    - hjsmin
    - extra
    - dhall
    - optparse-applicative
    - gitrev
    - file-embed

library:
    source-dirs:
        - src

executables:
    site:
        source-dirs: app
        main:        site/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        dependencies:
        - roki-web
    spa:
        source-dirs: app
        main:        spa/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        dependencies:
        - roki-web
        - transformers
